name: test

on: push

jobs:
  phpunit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Composer dependencies
      run: composer install --prefer-dist
           composer require composer require composer update

    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate

